from enum import Enum, auto


class StatusType(Enum):
    """Class that represents all possible statuses of a pokemon"""
    Normal = auto(),
    Fnt = auto(),
    Psn = auto(),
    Tox = auto(),
    Brn = auto(),
    Par = auto(),
    Frz = auto(),
    Slp = auto(),
    Attract = auto(),
    Confusion = auto(),
    Trapped = auto(),
    Protect = auto(),
    Endure = auto(),
    Flinch = auto(),
    Substitute = auto(),
    Taunt = auto(),
    Aquaring = auto(),
    Autotomize = auto(),
    Banefulbunker = auto(),
    Bide = auto(),
    Partiallytrapped = auto(),
    Charge = auto(),
    Curse = auto(),
    Defensecurl = auto(),
    Destinybond = auto(),
    Disable = auto(),
    Electrify = auto(),
    Embargo = auto(),
    Encore = auto(),
    Focusenergy = auto(),
    Followme = auto(),
    Foresight = auto(),
    Gastroacid = auto(),
    Grudge = auto(),
    Healblock = auto(),
    Helpinghand = auto(),
    Imprison = auto(),
    Ingrain = auto(),
    Kingsshield = auto(),
    Laserfocus = auto(),
    Leechseed = auto(),
    Magiccoat = auto(),
    Magnetrise = auto(),
    Minimize = auto(),
    Miracleeye = auto(),
    Nightmare = auto(),
    Powder = auto(),
    Powertrick = auto(),
    Ragepowder = auto(),
    Smackdown = auto(),
    Snatch = auto(),
    Spikyshield = auto(),
    Spotlight = auto(),
    Stockpile = auto(),
    Telekinesis = auto(),
    Throatchop = auto(),
    Torment = auto(),
    Yawn = auto()

